#!/bin/sh

export JAVA_CMD=/usr/lib/jvm/java-11-openjdk/bin/java

nextflow run main.nf \
	--input test/data/samplesheet.csv \
	--outdir results \
    --igenomes_base /home/hibari/job/aws-igenomes/references \
	--genome EB2 \
	-profile test \
	-config conf/custom.config \
	-work-dir work \
	-resume

