name: fastq_merge
description: Merge FASTQ files by sample
keywords:
  - preprocessing
  - fastq
tools:
  - cat:
      description: >
        The cat utility shall read files in sequence and shall write their
        contents to the standard output in the same sequence.
      documentation: http://man.cat-v.org/unix-1st/1/cat
      license: ["GPLv3"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads1:
      type: list
      description: |
        List of input FastQ files for read 1.
  - reads2:
      type: list
      description: |
        List of input FastQ files for read 2.
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads1:
      type: file
      description: >
        Output FastQ, a concatenation of the input FastQ files for read 1.
      pattern: "*.R1.{fastq.gz}"
  - reads2:
      type: file
      description: >
        Output FastQ, a concatenation of the input FastQ files for read 2.
      pattern: "*.R2.{fastq.gz}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@bahnk"
